export const legalContent = {
  fr: {
    legal: {
      title: 'Mentions légales', intro: 'Informations relatives à l’éditeur, à l’hébergement et à l’utilisation du site ardittiproduction.com.', updated: 'Mise à jour : 3 septembre 2026',
      sections: [
        { title: 'Éditeur du site', paragraphs: ['AR Production — Nathan Elie Samuel Arditti, entrepreneur individuel.', 'Adresse professionnelle : 2 boulevard Anatole France, 69006 Lyon, France.', 'SIREN : 928 617 539 · SIRET : 928 617 539 00012 · Code APE : 47.89Z.', 'Téléphone : +33 6 34 10 19 25 · Email : arditti.production@gmail.com.'] },
        { title: 'Direction de la publication', paragraphs: ['Directeur de la publication : Nathan Arditti.'] },
        { title: 'Hébergement', paragraphs: ['Le site est hébergé par Vercel Inc., 440 N Barranca Avenue #4133, Covina, CA 91723, États-Unis.', 'Site de l’hébergeur : vercel.com · Contact confidentialité : privacy@vercel.com.'] },
        { title: 'Propriété intellectuelle', paragraphs: ['La structure, les textes, éléments graphiques, vidéos, modèles 3D, démonstrations et signes distinctifs présents sur ce site sont protégés par le droit de la propriété intellectuelle. Sauf autorisation écrite préalable, toute reproduction, représentation, modification ou exploitation, totale ou partielle, est interdite.', 'Les marques, logos et contenus appartenant à des tiers restent la propriété de leurs titulaires respectifs et sont présentés uniquement pour illustrer les collaborations ou démonstrations concernées.'] },
        { title: 'Responsabilité et liens externes', paragraphs: ['AR Production veille à fournir des informations exactes et à maintenir le site accessible, sans pouvoir garantir l’absence totale d’erreur, d’interruption ou de contenu tiers indisponible. Les liens et démonstrations externes sont proposés à titre informatif ; leurs éditeurs restent responsables de leurs services et contenus.'] },
        { title: 'Données personnelles', paragraphs: ['Pour connaître les données collectées, leurs finalités et vos droits, consultez la politique de confidentialité du site.'] },
      ],
    },
    privacy: {
      title: 'Politique de confidentialité', intro: 'Cette politique explique comment AR Production traite les informations transmises sur ce site.', updated: 'Mise à jour : 3 septembre 2026',
      sections: [
        { title: 'Responsable du traitement', paragraphs: ['AR Production, représenté par Nathan Arditti, est responsable des traitements décrits ci-dessous.', 'Contact pour toute question ou demande relative à vos données : arditti.production@gmail.com.'] },
        { title: 'Données collectées', paragraphs: ['Lorsque vous utilisez le formulaire de contact, nous collectons les informations que vous renseignez : nom, téléphone éventuel, adresse email, type de produit, nombre de références, délai souhaité, offre sélectionnée et contenu du message.', 'La mesure d’audience peut collecter la page consultée, le site référent, le type d’appareil, le système d’exploitation, le navigateur, la résolution d’écran, le temps de chargement, la durée de session, une localisation approximative et les clics sur les boutons Démo ou Contact.'] },
        { title: 'Finalités et bases légales', paragraphs: ['Les informations du formulaire servent à répondre à votre demande, préparer un devis et prendre les mesures précontractuelles demandées par vos soins. Elles ne sont pas revendues.', 'Les données techniques servent à mesurer l’audience, comprendre l’utilisation des pages et améliorer les performances du site. Ce traitement repose sur l’intérêt légitime d’AR Production à administrer et améliorer son site, dans les limites applicables aux outils de mesure d’audience.'] },
        { title: 'Destinataires et prestataires', paragraphs: ['Les informations sont accessibles uniquement aux personnes habilitées d’AR Production et aux prestataires nécessaires au fonctionnement du service : Formspree pour la réception du formulaire, Discord lorsqu’une notification de nouveau message est activée, Vercel pour l’hébergement et AR Analytics pour les statistiques.', 'Certains prestataires peuvent traiter des données hors de l’Espace économique européen. Dans ce cas, les garanties prévues par la réglementation applicable doivent encadrer ces transferts.'] },
        { title: 'Durées de conservation', paragraphs: ['Les demandes de prospects sont conservées pendant la durée nécessaire à leur traitement, puis au maximum trois ans à compter de la collecte ou du dernier contact émanant du prospect, sauf obligation légale ou nécessité de conserver certains éléments pour défendre un droit.', 'Les données de mesure d’audience doivent être supprimées ou agrégées au plus tard après vingt-cinq mois. Le choix de langue reste enregistré sur votre appareil jusqu’à sa suppression par vos soins.'] },
        { title: 'Mesure d’audience et traceurs', paragraphs: ['AR Analytics utilise un identifiant de session aléatoire temporaire. Le script actuellement utilisé ne dépose pas de cookie publicitaire et ne crée pas de profil publicitaire. Vous pouvez désactiver la mesure d’audience pour ce navigateur avec le bouton ci-dessous.'] },
        { title: 'Vos droits', paragraphs: ['Vous pouvez demander l’accès, la rectification, l’effacement ou la limitation de vos données, vous opposer à certains traitements et exercer votre droit à la portabilité lorsque celui-ci s’applique. Écrivez à arditti.production@gmail.com en précisant votre demande.', 'Si vous estimez que vos droits ne sont pas respectés, vous pouvez déposer une réclamation auprès de la CNIL sur cnil.fr.'] },
        { title: 'Sécurité et mises à jour', paragraphs: ['Des mesures raisonnables sont mises en œuvre pour limiter l’accès non autorisé, la perte ou l’altération des informations. Cette politique pourra être mise à jour si les services, prestataires ou règles applicables évoluent.'] },
      ],
      analyticsOn: 'Les statistiques sont actives sur ce navigateur.', analyticsOff: 'Les statistiques sont désactivées sur ce navigateur.', disableAnalytics: 'Désactiver les statistiques', enableAnalytics: 'Réactiver les statistiques',
    },
  },
  en: {
    legal: {
      title: 'Legal notice', intro: 'Information about the publisher, hosting and use of ardittiproduction.com.', updated: 'Last updated: September 3, 2026',
      sections: [
        { title: 'Website publisher', paragraphs: ['AR Production — Nathan Elie Samuel Arditti, sole proprietor (entrepreneur individuel).', 'Business address: 2 boulevard Anatole France, 69006 Lyon, France.', 'SIREN: 928 617 539 · SIRET: 928 617 539 00012 · APE code: 47.89Z.', 'Phone: +33 6 34 10 19 25 · Email: arditti.production@gmail.com.'] },
        { title: 'Publication director', paragraphs: ['Publication director: Nathan Arditti.'] },
        { title: 'Hosting', paragraphs: ['The website is hosted by Vercel Inc., 440 N Barranca Avenue #4133, Covina, CA 91723, United States.', 'Hosting website: vercel.com · Privacy contact: privacy@vercel.com.'] },
        { title: 'Intellectual property', paragraphs: ['The structure, text, graphics, videos, 3D models, demonstrations and distinctive signs on this website are protected by intellectual property law. Unless prior written permission is obtained, any total or partial reproduction, representation, modification or use is prohibited.', 'Third-party trademarks, logos and content remain the property of their respective owners and are displayed solely to illustrate the relevant collaborations or demonstrations.'] },
        { title: 'Liability and external links', paragraphs: ['AR Production aims to provide accurate information and keep the website available, but cannot guarantee the complete absence of errors, interruptions or unavailable third-party content. External links and demonstrations are provided for information; their publishers remain responsible for their services and content.'] },
        { title: 'Personal data', paragraphs: ['For details about collected data, purposes and your rights, read the website privacy policy.'] },
      ],
    },
    privacy: {
      title: 'Privacy policy', intro: 'This policy explains how AR Production processes information submitted through this website.', updated: 'Last updated: September 3, 2026',
      sections: [
        { title: 'Data controller', paragraphs: ['AR Production, represented by Nathan Arditti, is responsible for the processing described below.', 'For questions or requests about your data, contact arditti.production@gmail.com.'] },
        { title: 'Data collected', paragraphs: ['When you use the contact form, we collect the information you provide: name, optional phone number, email address, product type, number of references, desired timeline, selected offer and message.', 'Audience measurement may collect the page viewed, referrer, device type, operating system, browser, screen resolution, load time, session duration, approximate location and clicks on Demo or Contact buttons.'] },
        { title: 'Purposes and legal grounds', paragraphs: ['Contact form information is used to answer your request, prepare a quote and take pre-contractual steps requested by you. It is not sold.', 'Technical data is used to measure audience, understand page usage and improve website performance. This processing is based on AR Production’s legitimate interest in administering and improving its website, within the limits applying to audience measurement tools.'] },
        { title: 'Recipients and providers', paragraphs: ['Information is accessible only to authorized AR Production personnel and the providers required to operate the service: Formspree for form delivery, Discord when new-message notifications are enabled, Vercel for hosting and AR Analytics for statistics.', 'Some providers may process data outside the European Economic Area. Where applicable, transfers must be covered by safeguards required under applicable law.'] },
        { title: 'Retention periods', paragraphs: ['Prospect enquiries are kept while they are processed and then for no longer than three years from collection or the prospect’s latest contact, unless a legal duty or the defense of a right requires certain information to be retained.', 'Audience data must be deleted or aggregated no later than twenty-five months after collection. Your language preference remains on your device until you remove it.'] },
        { title: 'Audience measurement and trackers', paragraphs: ['AR Analytics uses a temporary random session identifier. The current script does not set advertising cookies or create advertising profiles. You can disable audience measurement for this browser using the button below.'] },
        { title: 'Your rights', paragraphs: ['You may request access, correction, deletion or restriction of your data, object to certain processing and exercise data portability where applicable. Email arditti.production@gmail.com and describe your request.', 'If you believe your rights have not been respected, you may lodge a complaint with the French data protection authority, the CNIL, at cnil.fr.'] },
        { title: 'Security and updates', paragraphs: ['Reasonable measures are used to limit unauthorized access, loss or alteration. This policy may be updated if the services, providers or applicable rules change.'] },
      ],
      analyticsOn: 'Statistics are enabled on this browser.', analyticsOff: 'Statistics are disabled on this browser.', disableAnalytics: 'Disable statistics', enableAnalytics: 'Enable statistics',
    },
  },
} as const;
